server:
  port: 8081

spring:
  application:
    name: identity-service
  datasource:
    url: ${DB_EXTERNAL_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

grpc:
  server:
    port: 9090

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION} 
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${DB_DOCKER_URL}
  data:
    redis:
      host: redis
      port: 6379

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}