server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: redis
      port: 6379

  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.security.oauth2: DEBUG
      com.nimbusds.jose: DEBUG
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "${JWT_SECRET}"
          jws-algorithms: HS256
          
  cloud:
    gateway:
      
      grpc:
        enabled: false
      discovery:
        locator:
          enabled: true
          
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/auth/**, /api/admin/**, /api/users/**

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**, /api/media/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

grpc:
  client:
    identity-service:
      address: 'discovery:///identity-service'
      enable-keep-alive: true
      negotiation-type: plaintext

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value} 
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka/}